config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :moves, only: [:create]
  end
  root to: 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  before_validation(on: :create) do
    self.state = {
      0 => {0 => nil , 1 => nil , 2 => nil },
      1 => {0 => nil , 1 => nil , 2 => nil },
      2 => {0 => nil , 1 => nil , 2 => nil },
    }
    self.current_symbol = [:x, :o].sample #??
  end

  after_update_commit {broadcast_update}


  def [](row , col)
    state[row.to_s][col.to_s]
  end

  def move!(row, col)
      state[row.to_s][col.to_s] = current_symbol

  self.current_symbol = current_symbol == "x" ? "o" : "x"
  self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    redirect_to Game.create
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def create
    @game = Game.find(params[:game_id])
    @game.move!(params[:row], params[:col])

    respond_to do |format|
      format.turbo_stream
      format.html {
        redirect_to @game
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/games/_game.html.erb
<h1>GAME</h1>

<% 3.times do |row| %>
  <div class="row">
    <% 3.times do |col| %>
      <span class="cell">
        <% if !game[row , col].nil? %>
          <%= game[row, col] %>
        <% else %>
          <%= button_to game.current_symbol, game_moves_path(game), params: {row: row , col: col}, method: :post %>
        <% end %>
      </span>
    <% end %>
  </div>

<% end %>

app/views/games/index.html.erb
<h1>Games</h1>

<%= form_with(model: @game) do |form| %>
  <div>
    <%= form.submit "New Game" %>
  </div>
<% end %>

app/views/games/show.html.erb
<%= turbo_stream_from @game %>

<div id="<%= dom_id(@game)%>">
  <%= render @game %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictactoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>